### ISSUE TITLE
Release/tagged version?

### ISSUE THREAD

**Issue by apiri** [lucasvickers/osx-display-positioner#1]
Just curious as to what your overall thoughts were on the status of this little snippet of code.  With some wrapper scripts, this has been quite nice for hopping between various environments with my laptop.

I was interested in creating a Homebrew formula, but see that there is not a tagged version which would place the associated submission in the devel-only tap as per https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook.

Is it possible to get a tagged version and/or release?

**Comment by lucasvickers** [comment]
Very happy to hear you've found use in the software!  I have it running on a production environment and haven't had any issues.  I'll give it a tag as soon as my week calms down and let you know.

**Comment by apiri** [comment]
Awesome, glad to hear it, and certainly no rush.  Thanks!

**Comment by lucasvickers** [comment]
1.0 released!

**Comment by apiri** [comment]
Great! Will look to get this rolled into a formula when I find a few spare moments. Thanks for the release and your utility.
